FinanceBag/Controllers/ActiveController.cs
using FinanceBag.Models;
using FinanceBag.Repositories;
using Microsoft.AspNetCore.Mvc;


namespace FinanceBag.Controllers
{
    public class ActiveController : Controller
    {
        private readonly IBaseRepository<Active, string> _activeRepository;
        private readonly IBaseRepository<TypeOfActive, int> _typeOfActiveRepository;

        public ActiveController(IBaseRepository<Active, string> activeRepository, IBaseRepository<TypeOfActive, int> typeOfActiveRepository)
        {
            _activeRepository = activeRepository;
            _typeOfActiveRepository = typeOfActiveRepository;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Active> objActiv = await _activeRepository.GetAll();
            return View(objActiv);
        }

        //GET
        public async Task<IActionResult> Create()
        {
            ViewBag.Type = await _typeOfActiveRepository.GetAll();
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Active obj)
        {
            byte IsAvilible = 0;
            IEnumerable<Active> objActiv = await _activeRepository.GetAll();
            foreach (var item in objActiv)
            {
                if (item.ISIN_id == obj.ISIN_id.Trim(' ', '\t'))
                {
                    IsAvilible = 1;
                    break;
                }
            }
            if (IsAvilible == 0)
            {
                await _activeRepository.Insert(obj);
                await _activeRepository.Save();
                TempData["success"] = "Новая запись создана успешно";
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("ISIN_id", $"Запись {obj.ISIN_id} уже существет");
                ViewBag.Type = await _typeOfActiveRepository.GetAll();
                return View();
            }
        }

        //GET
        public async Task<IActionResult> Edit(string? id)
        {
            ViewBag.Type = await _typeOfActiveRepository.GetAll();
            if (id == null)
            {
                return NotFound();
            }
            var AtciveFromDb = await _activeRepository.GetById(id);
            if (AtciveFromDb == null)
            {
                return NotFound();
            }
            return View(AtciveFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Active obj)
        {
            await _activeRepository.Edit(obj);
            await _activeRepository.Save();
            TempData["success"] = "Запись отредактирована";
            return RedirectToAction("Index");
        }

        //GET
        public async Task<IActionResult> Delete(string? id)
        {
            ViewBag.Type = await _typeOfActiveRepository.GetAll();
            if (id == null)
            {
                return NotFound();
            }
            var AtciveFromDb = await _activeRepository.GetById(id);
            if (AtciveFromDb == null)
            {
                return NotFound();
            }
            return View(AtciveFromDb);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePOST(string? id)
        {
            await _activeRepository.Delete(id);
            await _activeRepository.Save();
            TempData["success"] = "Запись удалена";
            return RedirectToAction("Index");
        }
    }
}

FinanceBag/Controllers/DealController.cs
using FinanceBag.Data;
using FinanceBag.Models;
using FinanceBag.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FinanceBag.Controllers
{
    public class DealController : Controller
    {
        private readonly IBaseRepository<Active, string> _activeRepository;
        private readonly IBaseRepository<Deal, int> _dealRepository;
        private readonly IFilterRepository<Deal> _filterRepository;
        private readonly IViewBag _viewBagRepository;

        public DealController(IBaseRepository<Active, string> activeRepository, IBaseRepository<Deal, int> dealRepository,
            IFilterRepository<Deal> filterRepository, IViewBag viewBagRepository)
        {
            _activeRepository = activeRepository;
            _dealRepository = dealRepository;
            _filterRepository = filterRepository;
            _viewBagRepository = viewBagRepository; 
        }

        [HttpGet]
        public async Task<IActionResult> Index(string value0, string value1)
        {
            if(value0 == null && value1 == null)
            {
                IEnumerable<Deal> objDeal = await _dealRepository.GetAll();
                return View(objDeal);
            }
            IEnumerable<Deal> objDeal1 = await _filterRepository.FilterBy(value0, value1);
            return View(objDeal1);
        }

        //GET
        public async Task<IActionResult> Create()
        {
            ViewBag.ISIN_id = await _viewBagRepository.GetListToViewBag();
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Deal obj)
        {
            byte IsAvilible = 0;
            IEnumerable<Active> objActiv = await _activeRepository.GetAll();
            foreach (var item in objActiv)
            {
                if (item.ISIN_id == obj.ISIN_id.Trim(' ', '\t'))
                {
                    IsAvilible = 1;
                    break;
                }
            }
            if (IsAvilible == 1)
            {
            obj.Sum = obj.Count * obj.Price;
            await _dealRepository.Insert(obj);
            await _dealRepository.Save();
            TempData["success"] = "Новая запись создана успешно";
            return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("ISIN_id", $"Запись {obj.ISIN_id} не существует");
                ViewBag.ISIN_id = await _viewBagRepository.GetListToViewBag();
                return View();
            }
        }

        //GET
        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.ISIN_id = await _viewBagRepository.GetListToViewBag();
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var DealFromDb = await _dealRepository.GetById((int)id);
            if (DealFromDb == null)
            {
                return NotFound();
            }
            return View(DealFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Deal obj)
        {
            byte IsAvilible = 0;
            IEnumerable<Active> objActiv = await _activeRepository.GetAll();
            foreach (var item in objActiv)
            {
                if (item.ISIN_id == obj.ISIN_id.Trim(' ', '\t'))
                {
                    IsAvilible = 1;
                    break;
                }
            }
            if (IsAvilible == 1)
            {
                obj.Sum = obj.Count * obj.Price;
                await _dealRepository.Edit(obj);
                await _dealRepository.Save();
                TempData["success"] = "Запись отредактирована";
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("ISIN_id", $"Запись {obj.ISIN_id} не существует");
                ViewBag.ISIN_id = await _viewBagRepository.GetListToViewBag();
                return View();
            }
        }

        //GET
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var DealFromDb = await _dealRepository.GetById((int)id);
            if (DealFromDb == null)
            {
                return NotFound();
            }
            return View(DealFromDb);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePOST(int id)
        {
            await _dealRepository.Delete(id);
            await _dealRepository.Save();
            TempData["success"] = "Запись удалена";
            return RedirectToAction("Index");
        }

    }
}

FinanceBag/Controllers/GroupByMonthController.cs
using FinanceBag.Repositories;
using FinanceBag.Services;
using FinanceBag.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace FinanceBag.Controllers
{
    public class GroupByMonthController : Controller
    {
        private readonly IGroupRepository _repositoryGroup;
        private readonly IGroupByRequestHandlerService<List<GroupByMonthViewModel>> _groupByRequestHandler;

        public GroupByMonthController(IGroupRepository repositoryGroup, IGroupByRequestHandlerService<List<GroupByMonthViewModel>> groupByRequestHandler)
        {
            _repositoryGroup = repositoryGroup;
            _groupByRequestHandler = groupByRequestHandler;
        }
        public async Task<IActionResult> Index()
        {
            var objGroupByMonth = await _repositoryGroup.GroupByMonth();

            List<GroupByMonthViewModel> listGroupByMonthViewModels = new List<GroupByMonthViewModel>();
            listGroupByMonthViewModels = await _groupByRequestHandler.ExportToVM(objGroupByMonth);

            return View(listGroupByMonthViewModels);
            
        }
    }
}

FinanceBag/Controllers/TypeOfActiveController.cs
using FinanceBag.Models;
using FinanceBag.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace FinanceBag.Controllers
{
    public class TypeOfActiveController : Controller
    {
        private readonly IBaseRepository<TypeOfActive, int> _typeOfActiveRepository;

        public TypeOfActiveController(IBaseRepository<TypeOfActive, int> typeOfActiveRepository)
        {
            _typeOfActiveRepository = typeOfActiveRepository;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<TypeOfActive> objTypeOfActiv = await _typeOfActiveRepository.GetAll();
            return View(objTypeOfActiv);

        }
        // GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TypeOfActive obj)
        {
            byte IsAvilible = 0;
            IEnumerable<TypeOfActive> objTypeOfActiv = await _typeOfActiveRepository.GetAll();
            foreach (var item in objTypeOfActiv)
            {
                if (item.Type == obj.Type.Trim(' ', '\t'))
                {
                    IsAvilible = 1;
                    break;
                }
            }
            if (IsAvilible == 0)
            {
                await _typeOfActiveRepository.Insert(obj);
                await _typeOfActiveRepository.Save();
                TempData["success"] = "Новая запись создана успешно";
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("Type", $"Запись {obj.Type} уже существет");
                return View();
            }
        }

        //GET
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var TypeOfAtciveFromDb = await _typeOfActiveRepository.GetById((int)id);
            if (TypeOfAtciveFromDb == null)
            {
                return NotFound();
            }
            return View(TypeOfAtciveFromDb);
        }

       // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(TypeOfActive obj)
        {
                await _typeOfActiveRepository.Edit(obj);
                await _typeOfActiveRepository.Save();
                TempData["success"] = "Запись отредактирована";
                return RedirectToAction("Index");
        }


        //GET
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var TypeOfAtciveFromDb = await _typeOfActiveRepository.GetById((int)id);
            if (TypeOfAtciveFromDb == null)
            {
                return NotFound();
            }
            return View(TypeOfAtciveFromDb);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePOST(int id)
        {
            await _typeOfActiveRepository.Delete(id);
            await _typeOfActiveRepository.Save();
            TempData["success"] = "Запись удалена";
            return RedirectToAction("Index");
        }
    }
}

FinanceBag/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinanceBag</title>
@*    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/bootswatchTheme.css"/>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FinanceBag.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Портфель</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div style="margin-right: 5px;">
                    <div class="dropdown">
                        <a class="btn btn-outline-secondary dropdown-toggle"  href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Аналитика
                        </a>
                        <ul class="dropdown-menu">
                        <li><a class="dropdown-item" asp-controller="GroupByMonth" asp-action="Index">Затраты по месяцам</a></li>
                        </ul>
                    </div>
                </div>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <div class="dropdown" >
                        <a class="btn btn-outline-secondary dropdown-toggle"  href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Справочники
                        </a>
                        <ul class="dropdown-menu">
                        <li><a class="dropdown-item" asp-controller="TypeOfActive" asp-action="Index">Типы активов</a></li>
                        <li><a class="dropdown-item" asp-controller="Active" asp-action="Index">Активы</a></li>
                        <li><a class="dropdown-item" asp-controller="Deal" asp-action="Index">Сделки</a></li>
                        </ul>
                    </div>
                </div>



            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
           @* &copy; 2022 - FinanceBag - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js"
    integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FinanceBag/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
	</script>
}